# Generated by Django 4.0.2 on 2022-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DecimalField(decimal_places=20, max_digits=50)),
                ('primary_mass', models.DecimalField(decimal_places=20, max_digits=50)),
                ('primary_radius', models.DecimalField(decimal_places=20, max_digits=50)),
                ('primary_luminosity', models.DecimalField(decimal_places=20, max_digits=50)),
                ('primary_temperature', models.DecimalField(decimal_places=20, max_digits=50)),
                ('secondary_mass', models.DecimalField(decimal_places=20, max_digits=50)),
                ('secondary_radius', models.DecimalField(decimal_places=20, max_digits=50)),
                ('secondary_luminosity', models.DecimalField(decimal_places=20, max_digits=50)),
                ('secondary_temperature', models.DecimalField(decimal_places=20, max_digits=50)),
                ('mass_ratio', models.DecimalField(decimal_places=20, max_digits=50)),
            ],
            options={
                'db_table': 'EBs_Data',
            },
        ),
    ]
